version: '3.1'

services:

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - 8989:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: stars_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql_db
    restart: always
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password